apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiops-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/websocket-services: "aiops-backend-service"
spec:
  rules:
    - host: ops.sharmaelectricals.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: aiops-backend-service
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: aiops-backend-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aiops-frontend-service
                port:
                  number: 80
