apiVersion: v1
kind: Secret
metadata:
  name: aiops-secret
  labels:
    app.kubernetes.io/name: aiops-saas
type: Opaque
stringData:
  POSTGRES_USER: "aiops_user"
  POSTGRES_PASSWORD: "aiops_secure_password_2026"
  JWT_SECRET: "c2VjdXJlLWVudGVycHJpc2UtYWlvcHMtaW5kaWEta2V5LTIwMjYtcHJvZHVjdGlvbi1zYWFzLWNoZWNrc3Vt"
